"""
FraudControl API v2 — Fully Autonomous Agentic Backend.

New in v2:
  - THINKING_UPDATE WebSocket events stream agent reasoning steps to the UI in real-time.
  - ACTION_TAKEN WebSocket events report what the Action Agent actually did (block/hold/approve).
  - POST /api/investigate — manual investigation trigger for human-in-the-loop demos.
  - GET  /api/blocked-accounts — live registry of autonomously blocked accounts.
  - GET  /api/alerts — priority alert feed generated by the Action Agent.
  - GET  /api/stats — aggregate dashboard statistics.
  - Memory Agent results are stored to SQLite after every SLOW_PATH investigation.
"""
import os
import sys
import json
import asyncio
import uuid
import pandas as pd
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from aiokafka import AIOKafkaConsumer

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

from ml_engine import predict_risk
from agent_engine import (
    TransactionData,
    CustomerData,
    initialize_policy_index,
    investigate,
    set_thinking_callback,
)
import action_engine
import memory_engine

app = FastAPI(title="FraudControl — Autonomous Agentic Fraud Investigation API v2")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── WebSocket Connection Manager ──────────────────────────────────────────────

class ConnectionManager:
    def __init__(self):
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)

    async def broadcast(self, message: dict):
        dead = []
        for connection in self.active_connections:
            try:
                await connection.send_json(message)
            except Exception:
                dead.append(connection)
        for d in dead:
            self.disconnect(d)

manager = ConnectionManager()

# Authoritative dashboard state for WebSocket reconnects/page refreshes.
# Records are inserted on FAST_PATH and enriched by SLOW_PATH/ACTION_TAKEN.
dashboard_transactions: dict[str, dict] = {}


# ── Register Thinking Callback in Agent Engine ────────────────────────────────

async def _broadcast_thinking(agent_name: str, message: str, step_index: int, customer_id: str = None):
    """Called by agent_engine.py to stream real-time reasoning steps."""
    await manager.broadcast({
        "type": "THINKING_UPDATE",
        "agent": agent_name,
        "message": message,
        "step_index": step_index,
        "customer_id": customer_id,
    })

set_thinking_callback(_broadcast_thinking)


# ── Config ────────────────────────────────────────────────────────────────────

KAFKA_BROKER = os.getenv("KAFKA_BROKER", "localhost:9092")
TOPIC = os.getenv("KAFKA_TOPIC", "transactions-in")
CLOUDAMQP_URL = os.getenv("CLOUDAMQP_URL")

NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "fraudcontrol")

slow_path_semaphore = asyncio.Semaphore(1)

from neo4j import AsyncGraphDatabase


# ── Neo4j Graph Ingestion ─────────────────────────────────────────────────────

async def ingest_to_graph(tx: dict, prof: dict):
    try:
        driver = AsyncGraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
        async with driver.session() as session:
            query = """
            MERGE (u:User {id: $customer_id})
            MERGE (t:TransactionNode {id: $tx_id})
            SET t.amount = $amount, t.type = $type
            MERGE (u)-[:PERFORMED]->(t)
            """
            import uuid
            await session.run(query,
                customer_id=tx['customer_id'],
                tx_id=str(tx.get('step', '0')) + "_" + tx['customer_id'] + "_" + uuid.uuid4().hex[:8],
                amount=float(tx['amount']),
                type=tx['type']
            )
        await driver.close()
        print(f"Ingested TX {tx['customer_id']} to Neo4j")
    except Exception as e:
        print(f"Graph ingestion failed: {e}")


# ── Core Message Processor ────────────────────────────────────────────────────

async def process_message(msg_value):
    try:
        data = json.loads(msg_value.decode('utf-8'))
        tx = data["transaction"]
        prof = data["profile"]

        # 0. Continuous graph ingestion (fire-and-forget)
        asyncio.create_task(ingest_to_graph(tx, prof))

        # 1. Fast Path: XGBoost + TabNet
        result = predict_risk(tx)
        transaction_id = str(
            tx.get("transaction_id")
            or f"{tx.get('step', '0')}:{tx['customer_id']}:{tx.get('nameDest', '')}"
        )
        action_engine.register_transaction(
            transaction_id=transaction_id,
            customer_id=tx["customer_id"],
            is_flagged=result["is_flagged"],
        )

        fast_path_payload = {
            "type": "FAST_PATH",
            "transaction_id": transaction_id,
            "transaction": tx,
            "profile": prof,
            "fast_path_result": result,
            "stats": action_engine.get_action_stats(),
            "blocked_accounts": action_engine.blocked_accounts[-10:],
            "alerts": action_engine.alert_feed[-8:],
        }
        dashboard_transactions[transaction_id] = {
            "id": transaction_id,
            "transaction": tx,
            "profile": prof,
            "fastPathResult": result,
            "report": None,
            "actionResult": None,
            "manual": False,
        }
        await manager.broadcast(fast_path_payload)

        # 2. Slow Path (only if flagged)
        if result["is_flagged"]:
            tx_data = TransactionData(
                customer_id=tx["customer_id"],
                type=tx["type"],
                amount=tx["amount"],
                oldbalanceOrg=tx["oldbalanceOrg"],
                oldbalanceDest=tx["oldbalanceDest"],
                risk_score=result["risk_score"],
                ml_flagged=result["is_flagged"],
            )
            cust_data = CustomerData(
                customer_id=prof["customer_id"],
                kyc_status=prof["kyc_status"],
                pep_status=bool(prof["pep_status"]),
                risk_tier=prof["risk_tier"],
                account_age_days=int(prof["account_age_days"]),
                unique_counterparties_30d=int(prof["unique_counterparties_30d"]),
                shared_ip_count=int(prof["shared_ip_count"]),
                recent_failed_logins=int(prof["recent_failed_logins"]),
                session_velocity_seconds=int(prof["session_velocity_seconds"]),
                historical_avg_tx_amount=float(prof["historical_avg_tx_amount"]),
            )

            async with slow_path_semaphore:
                report = await investigate(tx_data, cust_data)

            # 3. Action Agent: autonomously execute the decision
            action_result = await action_engine.execute_action(
                customer_id=tx["customer_id"],
                recommended_action=report.recommended_action,
                risk_score=report.risk_score,
                reasons=report.reasons,
                sar_explanation=report.sar_explanation,
                transaction_amount=float(tx["amount"]),
                transaction_type=tx["type"],
                transaction_id=transaction_id,
            )

            # 4. Memory Agent: persist this investigation for future reference
            memory_engine.store_investigation(
                customer_id=tx["customer_id"],
                risk_score=report.risk_score,
                action=report.recommended_action,
                flags=report.reasons,
                explanation=report.sar_explanation,
                tx_amount=float(tx["amount"]),
                tx_type=tx["type"],
            )

            # 5. Broadcast SLOW_PATH result
            slow_path_payload = {
                "type": "SLOW_PATH",
                "transaction_id": transaction_id,
                "customer_id": tx["customer_id"],
                "report": report.model_dump(),
            }
            dashboard_transactions[transaction_id]["report"] = report.model_dump()
            await manager.broadcast(slow_path_payload)

            # 6. Broadcast ACTION_TAKEN event
            dashboard_transactions[transaction_id]["actionResult"] = action_result
            await manager.broadcast({
                "type": "ACTION_TAKEN",
                "transaction_id": transaction_id,
                "customer_id": tx["customer_id"],
                "action_result": action_result,
                "stats": action_engine.get_action_stats(),
                "blocked_accounts": action_engine.blocked_accounts[-10:],
                "alerts": action_engine.alert_feed[-8:],
            })

    except Exception as e:
        print(f"Error processing message: {e}")
        import traceback; traceback.print_exc()


# ── Message Queue Consumers ───────────────────────────────────────────────────

async def rabbitmq_consumer_task():
    import aio_pika
    print(f"Connecting to RabbitMQ/CloudAMQP at {CLOUDAMQP_URL}...")

    connection = None
    for _ in range(5):
        try:
            connection = await aio_pika.connect_robust(CLOUDAMQP_URL)
            break
        except Exception as e:
            print(f"Waiting for RabbitMQ... {e}")
            await asyncio.sleep(2)

    if not connection:
        print("Failed to connect to RabbitMQ.")
        return

    print("RabbitMQ/CloudAMQP Consumer started successfully!")
    async with connection:
        channel = await connection.channel()
        queue = await channel.declare_queue(TOPIC, durable=True)

        async with queue.iterator() as queue_iter:
            async for message in queue_iter:
                async with message.process():
                    asyncio.create_task(process_message(message.body))


async def kafka_consumer_task():
    consumer = AIOKafkaConsumer(
        TOPIC,
        bootstrap_servers=KAFKA_BROKER,
        group_id="fraud-consumer-group",
        auto_offset_reset="latest"
    )
    for _ in range(5):
        try:
            await consumer.start()
            break
        except Exception:
            await asyncio.sleep(2)

    print("Kafka Consumer started successfully!")
    try:
        async for msg in consumer:
            asyncio.create_task(process_message(msg.value))
    finally:
        await consumer.stop()


@app.on_event("startup")
async def startup_event():
    # Build or load the RAG policy index before accepting transaction work.
    # This avoids paying the indexing cost during the first flagged message.
    await initialize_policy_index()

    if CLOUDAMQP_URL:
        asyncio.create_task(rabbitmq_consumer_task())
    else:
        asyncio.create_task(kafka_consumer_task())


# ── WebSocket Endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws/stream")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    # Send initial stats on connection
    await websocket.send_json({
        "type": "INIT",
        "stats": action_engine.get_action_stats(),
        "blocked_accounts": action_engine.blocked_accounts[-10:],
        "alerts": action_engine.alert_feed[-5:],
        "transactions": list(reversed(dashboard_transactions.values())),
    })
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(websocket)


# ── REST Endpoints ────────────────────────────────────────────────────────────

@app.get("/api/blocked-accounts")
async def get_blocked_accounts():
    """Live registry of autonomously blocked accounts."""
    return {
        "count": len(action_engine.blocked_accounts),
        "accounts": list(reversed(action_engine.blocked_accounts)),  # newest first
    }


@app.get("/api/alerts")
async def get_alerts():
    """Priority alert feed for human investigators."""
    return {
        "count": len(action_engine.alert_feed),
        "alerts": list(reversed(action_engine.alert_feed)),  # newest first
    }


@app.get("/api/stats")
async def get_stats():
    """Aggregate statistics for the dashboard."""
    return action_engine.get_action_stats()


@app.get("/api/audit-log")
async def get_audit_log(limit: int = 50):
    """Full audit trail of every action taken by the Action Agent."""
    return {
        "count": len(action_engine.audit_log),
        "entries": list(reversed(action_engine.audit_log))[:limit],
    }


# ── Managed Stream Control (On-Demand & Idle Auto-Pause) ──────────────────────

is_producer_running = False
producer_task = None

@app.get("/api/stream/status")
async def get_stream_status():
    """Return streaming status and active UI client count."""
    return {
        "is_streaming": is_producer_running,
        "active_ui_clients": len(manager.active_connections)
    }

@app.post("/api/stream/start")
async def start_stream(interval_seconds: int = 20):
    """Start streaming transactions on-demand."""
    global is_producer_running, producer_task
    if is_producer_running:
        return {"status": "already_running"}
    is_producer_running = True
    producer_task = asyncio.create_task(run_managed_stream(interval_seconds))
    return {"status": "started", "interval_seconds": interval_seconds}

@app.post("/api/stream/stop")
async def stop_stream():
    """Stop/pause streaming transactions immediately to save credits."""
    global is_producer_running
    is_producer_running = False
    return {"status": "stopped"}

async def run_managed_stream(interval_seconds: int = 20):
    """Managed background transaction stream loop with auto-pause guardrails."""
    global is_producer_running
    print(f"[Managed Stream] Producer loop started (Interval: {interval_seconds}s).")
    idle_count = 0
    try:
        data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
        tx_path = os.path.join(data_dir, "aligned_transactions.csv")
        prof_path = os.path.join(data_dir, "customer_profiles.csv")
        
        if not os.path.exists(tx_path) or not os.path.exists(prof_path):
            print("[Managed Stream] Data files missing.")
            is_producer_running = False
            return

        tx_df = pd.read_csv(tx_path)
        profiles_df = pd.read_csv(prof_path).set_index("customer_id")

        for _, tx_row in tx_df.iterrows():
            if not is_producer_running:
                break
            
            # Idle Auto-Stop Timeout: auto-pause if no UI clients connected for 2+ minutes
            if len(manager.active_connections) == 0:
                idle_count += interval_seconds
                if idle_count >= 120:
                    print("[Managed Stream] Auto-pausing stream: No active UI connected for 2 minutes.")
                    is_producer_running = False
                    break
            else:
                idle_count = 0

            cust_id = tx_row['customer_id']
            if cust_id not in profiles_df.index:
                continue

            tx_dict = {k: (None if pd.isna(v) else v) for k, v in tx_row.to_dict().items()}
            prof_dict = {k: (None if pd.isna(v) else v) for k, v in profiles_df.loc[cust_id].to_dict().items()}
            prof_dict["customer_id"] = cust_id

            msg_payload = json.dumps({"transaction": tx_dict, "profile": prof_dict}).encode('utf-8')
            await process_message(msg_payload)
            await asyncio.sleep(interval_seconds)
    except Exception as e:
        print(f"[Managed Stream] Exception in stream loop: {e}")
    finally:
        is_producer_running = False
        print("[Managed Stream] Producer loop stopped.")


# ── Manual Investigation Trigger ──────────────────────────────────────────────

class ManualInvestigationRequest(BaseModel):
    customer_id: str = "C1539299608"
    type: str = "TRANSFER"
    amount: float = 1_241_118.86
    oldbalanceOrg: float = 1_241_118.86
    oldbalanceDest: float = 0.0
    kyc_status: str = "Pending"
    pep_status: bool = False
    risk_tier: str = "High (Network Risk)"
    account_age_days: int = 42
    unique_counterparties_30d: int = 38
    shared_ip_count: int = 20
    recent_failed_logins: int = 4
    session_velocity_seconds: int = 3
    historical_avg_tx_amount: float = 890.50


@app.post("/api/investigate")
async def manual_investigate(req: ManualInvestigationRequest):
    """
    Human-in-the-loop: manually trigger the full agent investigation workflow.
    Useful for demos — paste any customer/transaction data and watch the agents work.
    Results are also broadcast via WebSocket so the dashboard updates live.
    """
    from ml_engine import predict_risk

    tx_dict = {
        "customer_id": req.customer_id,
        "type": req.type,
        "amount": req.amount,
        "oldbalanceOrg": req.oldbalanceOrg,
        "oldbalanceDest": req.oldbalanceDest,
        "step": 0,
        "isFlaggedFraud": 0,
    }
    ml_result = predict_risk(tx_dict)
    transaction_id = f"manual:{req.customer_id}:{uuid.uuid4().hex}"
    action_engine.register_transaction(
        transaction_id=transaction_id,
        customer_id=req.customer_id,
        is_flagged=True,
    )

    tx_data = TransactionData(
        customer_id=req.customer_id,
        type=req.type,
        amount=req.amount,
        oldbalanceOrg=req.oldbalanceOrg,
        oldbalanceDest=req.oldbalanceDest,
        risk_score=ml_result.get("risk_score", 85.0),
        ml_flagged=True,  # Manual trigger always runs the slow path
    )
    cust_data = CustomerData(
        customer_id=req.customer_id,
        kyc_status=req.kyc_status,
        pep_status=req.pep_status,
        risk_tier=req.risk_tier,
        account_age_days=req.account_age_days,
        unique_counterparties_30d=req.unique_counterparties_30d,
        shared_ip_count=req.shared_ip_count,
        recent_failed_logins=req.recent_failed_logins,
        session_velocity_seconds=req.session_velocity_seconds,
        historical_avg_tx_amount=req.historical_avg_tx_amount,
    )

    dashboard_transactions[transaction_id] = {
        "id": transaction_id,
        "transaction": tx_dict,
        "profile": req.model_dump(),
        "fastPathResult": {**ml_result, "is_flagged": True},
        "report": None,
        "actionResult": None,
        "manual": True,
    }
    # Broadcast FAST_PATH for UI first
    await manager.broadcast({
        "type": "FAST_PATH",
        "transaction_id": transaction_id,
        "transaction": tx_dict,
        "profile": req.model_dump(),
        "fast_path_result": {**ml_result, "is_flagged": True},
        "stats": action_engine.get_action_stats(),
        "blocked_accounts": action_engine.blocked_accounts[-10:],
        "alerts": action_engine.alert_feed[-8:],
        "manual_trigger": True,
    })

    # Run full investigation
    report = await investigate(tx_data, cust_data)

    action_result = await action_engine.execute_action(
        customer_id=req.customer_id,
        recommended_action=report.recommended_action,
        risk_score=report.risk_score,
        reasons=report.reasons,
        sar_explanation=report.sar_explanation,
        transaction_amount=req.amount,
        transaction_type=req.type,
        transaction_id=transaction_id,
    )

    memory_engine.store_investigation(
        customer_id=req.customer_id,
        risk_score=report.risk_score,
        action=report.recommended_action,
        flags=report.reasons,
        explanation=report.sar_explanation,
        tx_amount=req.amount,
        tx_type=req.type,
    )

    dashboard_transactions[transaction_id]["report"] = report.model_dump()
    await manager.broadcast({
        "type": "SLOW_PATH",
        "transaction_id": transaction_id,
        "customer_id": req.customer_id,
        "report": report.model_dump(),
        "manual_trigger": True,
    })

    dashboard_transactions[transaction_id]["actionResult"] = action_result
    await manager.broadcast({
        "type": "ACTION_TAKEN",
        "transaction_id": transaction_id,
        "customer_id": req.customer_id,
        "action_result": action_result,
        "stats": action_engine.get_action_stats(),
        "blocked_accounts": action_engine.blocked_accounts[-10:],
        "alerts": action_engine.alert_feed[-8:],
    })

    return {
        "status": "complete",
        "report": report.model_dump(),
        "action_taken": action_result,
    }


# ── OTP Verification & HITL Override Endpoints ────────────────────────────────

class VerifyOTPRequest(BaseModel):
    customer_id: str
    code: str

class HITLOverrideRequest(BaseModel):
    customer_id: str
    action: str  # Approve | Block
    notes: str = ""

@app.post("/api/verify-otp")
async def verify_otp(req: VerifyOTPRequest):
    """Customer OTP step-up verification."""
    result = action_engine.verify_customer_otp(req.customer_id, req.code)
    if result["success"]:
        transaction_id = result["action_result"].get("transaction_id")
        if transaction_id in dashboard_transactions:
            dashboard_transactions[transaction_id]["actionResult"] = result["action_result"]
        await manager.broadcast({
            "type": "ACTION_TAKEN",
            "transaction_id": result["action_result"].get("transaction_id"),
            "customer_id": req.customer_id,
            "action_result": result["action_result"],
            "stats": action_engine.get_action_stats(),
            "blocked_accounts": action_engine.blocked_accounts[-10:],
            "alerts": action_engine.alert_feed[-8:],
        })
    return result

@app.post("/api/hitl-override")
async def hitl_override(req: HITLOverrideRequest):
    """Human-In-The-Loop (HITL) compliance officer manual override."""
    result = action_engine.hitl_override_action(req.customer_id, req.action, req.notes)
    if result["success"]:
        transaction_id = result["action_result"].get("transaction_id")
        if transaction_id in dashboard_transactions:
            dashboard_transactions[transaction_id]["actionResult"] = result["action_result"]
        await manager.broadcast({
            "type": "ACTION_TAKEN",
            "transaction_id": result["action_result"].get("transaction_id"),
            "customer_id": req.customer_id,
            "action_result": result["action_result"],
            "stats": action_engine.get_action_stats(),
            "blocked_accounts": action_engine.blocked_accounts[-10:],
            "alerts": action_engine.alert_feed[-8:],
        })
    return result
